# 使用官方提供的基础镜像
FROM easytier/easytier:latest

# 设置工作目录
WORKDIR /app

# 设置时区为上海
RUN apk add tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone \
    && apk del tzdata

# 定义容器启动时执行的命令
ENTRYPOINT ["easytier-core"]
